# Generated by Django 4.2.4 on 2023-11-11 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="ranking",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
