# Generated by Django 4.2.4 on 2023-11-28 03:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
