# Generated by Django 4.2.4 on 2023-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
